[SERVICE]
    Flush         5
    Log_Level     info
    Daemon        off

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*
    Refresh_Interval  5
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On

[OUTPUT]
    Name               es
    Match              docker.*
    Host               elasticsearch
    Port               9200
    Index              docker-logs
    Suppress_Type_Name On
    Logstash_Format    On
    Logstash_Prefix    docker-logs
    Retry_Limit        5